In [1]:
import numpy as np
samplepoints=np.array([(2,4),(4,2),(4,4),(4,6),(6,2),(6,4)])
print(samplepoints)

[[2 4]
 [4 2]
 [4 4]
 [4 6]
 [6 2]
 [6 4]]


In [2]:
colorarray=np.array([0,0,1,0,1,0])
print(colorarray)

[0 0 1 0 1 0]


In [3]:
Distancearray=[]
k=3
tofind=np.array([(6,6)])
print(tofind)
print(tofind[0][0])

[[6 6]]
6


In [4]:
for i in range(0,len(samplepoints)):
    q=((samplepoints[i][0]-tofind[0][0])**2)+((samplepoints[i][1]-tofind[0][1])**2)
    Distancearray.append(q)
    print(Distancearray)
    


[20]
[20, 20]
[20, 20, 8]
[20, 20, 8, 4]
[20, 20, 8, 4, 16]
[20, 20, 8, 4, 16, 4]


In [5]:
print(Distancearray)
ziparray=zip(Distancearray,colorarray)
print(ziparray)

[20, 20, 8, 4, 16, 4]


In [6]:
Listarray=list(ziparray)
print(Listarray)

[(20, 0), (20, 0), (8, 1), (4, 0), (16, 1), (4, 0)]


In [7]:
Listarray.sort()
print(Listarray)

[(4, 0), (4, 0), (8, 1), (16, 1), (20, 0), (20, 0)]


In [8]:
Listarray=Listarray[0:k]
print(Listarray)

[(4, 0), (4, 0), (8, 1)]


In [9]:
temp0=0
temp1=0
for i in range(0,k):
    if Listarray[i][1]==0:
        temp0=temp0+1;
    else:
        temp1=temp1+1;
    
print(temp0)
print(temp1)

2
1
